apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: monitor
  name: monitor
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: monitor
    spec:
      containers:
      - env:
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              key: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
              name: monitor-docker-compose-env
        - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
          valueFrom:
            configMapKeyRef:
              key: APPDYNAMICS_AGENT_ACCOUNT_NAME
              name: monitor-docker-compose-env
        - name: APPDYNAMICS_AGENT_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              key: APPDYNAMICS_AGENT_APPLICATION_NAME
              name: monitor-docker-compose-env
        - name: APPDYNAMICS_CONTROLLER_HOST_NAME
          valueFrom:
            configMapKeyRef:
              key: APPDYNAMICS_CONTROLLER_HOST_NAME
              name: monitor-docker-compose-env
        - name: APPDYNAMICS_CONTROLLER_PORT
          valueFrom:
            configMapKeyRef:
              key: APPDYNAMICS_CONTROLLER_PORT
              name: monitor-docker-compose-env
        - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
          valueFrom:
            configMapKeyRef:
              key: APPDYNAMICS_CONTROLLER_SSL_ENABLED
              name: monitor-docker-compose-env
        - name: APPD_AGENT_SHA256
          valueFrom:
            configMapKeyRef:
              key: APPD_AGENT_SHA256
              name: monitor-docker-compose-env
        - name: APPD_AGENT_VERSION
          valueFrom:
            configMapKeyRef:
              key: APPD_AGENT_VERSION
              name: monitor-docker-compose-env
        - name: APPD_DIR
          valueFrom:
            configMapKeyRef:
              key: APPD_DIR
              name: monitor-docker-compose-env
        - name: APPD_ES_HOST
          valueFrom:
            configMapKeyRef:
              key: APPD_ES_HOST
              name: monitor-docker-compose-env
        - name: APPD_ES_PORT
          valueFrom:
            configMapKeyRef:
              key: APPD_ES_PORT
              name: monitor-docker-compose-env
        - name: APPD_ES_SSL
          valueFrom:
            configMapKeyRef:
              key: APPD_ES_SSL
              name: monitor-docker-compose-env
        - name: APPD_EVENT_ACCOUNT_NAME
          valueFrom:
            configMapKeyRef:
              key: APPD_EVENT_ACCOUNT_NAME
              name: monitor-docker-compose-env
        - name: RETRY
          valueFrom:
            configMapKeyRef:
              key: RETRY
              name: monitor-docker-compose-env
        - name: TIMEOUT
          valueFrom:
            configMapKeyRef:
              key: TIMEOUT
              name: monitor-docker-compose-env
        image: appddemo/appdynamics-monitor
        name: monitor
        resources: {}
        volumeMounts:
        - mountPath: /project
          name: project
        - mountPath: /hostroot
          name: monitor-claim1
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: monitor-claim2
      restartPolicy: Always
      volumes:
      - name: project
        persistentVolumeClaim:
          claimName: project
      - name: monitor-claim1
        persistentVolumeClaim:
          claimName: monitor-claim1
          readOnly: true
      - name: monitor-claim2
        persistentVolumeClaim:
          claimName: monitor-claim2
status: {}
