apiVersion: v1
kind: Pod
metadata:
  name: project
spec:
  containers:
  - image: appddemo/adcapital-project
    name: project
    resources: {}
    volumeMounts:
    - mountPath: /project
      name: project
  restartPolicy: Never
  volumes:
  - name: project
    persistentVolumeClaim:
      claimName: project
status: {}
