apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: project
  name: project
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: project
    spec:
      containers:
      - image: appddemo/adcapital-project
        name: project
        resources: {}
        volumeMounts:
        - mountPath: /project
          name: project
      volumes:
      - name: project
        persistentVolumeClaim:
          claimName: project
status: {}
